version: 0.2

phases:
  install:
    runtime-versions:
        docker: 18     
    commands: 
      #- nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      # - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - pip install detect-secrets
      - which detect-secrets
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - detect-secrets  scan > gitsecret_report.json
      - cat gitsecret_report.json
      -  time=$(date +'%Y-%m-%d')        
	  -	sudo curl --location --request POST 'http://52.14.192.9:8080/api/v2/import-scan/' 
--header 'Authorization: Token a1c2e4b944e0ba004336bccc9ec5dd2fcfdba1b2' 
--form 'engagement="2"' 
--form 'verified="true"' 
--form 'active="true"' 
--form 'lead="1"' 
--form tags=$BUILD_NUMBER 
--form scan_date=$date 
--form 'scan_type="Detect-secrets Scan"' 
--form 'minimum_severity="Info"' 
--form 'skip_duplicates="true"' 
--form 'close_old_findings="false"' 
--form 'file=@"gitsecret_report.json"'


      - pwd
      - ls -lrth
      
      #- echo Setting up docker
      #- nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      #- timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - chmod 777 owasp-dependency-check.sh
      - ./owasp-dependency-check.sh
      #- ls -lrth /odc-reports
      - cat dependency-check-report.xml
      - ls -lrth
      

  build:
    commands:
      - echo Build started on `date`
     
  post_build:
    commands:
      - echo Build completed on `date`
